### Create User
# @no-cookie-jar
POST http://localhost:8080/api/user/create
Content-Type: application/json

{
  "first_name": "Harry",
  "last_name": "Potter",
  "email": "testa@example.com",
  "password": "incendio.Aguamenti7+"
}
